### ISSUE TITLE
Replace hyphens in backend labels

### ISSUE THREAD

**Issue by rolandschuetz** [CarbonPackages/Carbon.Hyphen#3]
**Describe the bug**
If a title includes a hyphen replacement (||), document trees easily start to look bad.

**To Reproduce**
1. Create a page with the Title "Car||bon.Hy||phen"
2. It looks bad in the administration document tree

**Expected behavior**
Clearly readable document name "Carbon.Hyphen".

**Additional context**
I don't know a generic way to solve this problem for all configurable [translation rules](https://github.com/CarbonPackages/Carbon.Hyphen/blob/master/Configuration/Settings.yaml#L3). The default hyphen can be replaced easily in Neos.Neos:Node with [this code](
https://github.com/neos/Neos.DocsNeosIo/blob/master/DistributionPackages/Neos.DocsNeosIo/Configuration/NodeTypes.Override.Node.yaml).

**Comment by jonnitto** [comment]
Good catch. The problem with the code above is, that the double pipes get also removed in the frontend. `Neos.Neos:Menu` use `node.label` to show the label of the navigation item. I expanded your code a bit: I replace the `||` only in the backend and make it also configurable. But thank you a lot for this issue!

**Comment by jonnitto** [comment]
Here the Release: https://github.com/CarbonPackages/Carbon.Hyphen/releases/tag/1.1.0

**Comment by rolandschuetz** [comment]
Cool, thanks a lot for the super quick fix :)
